#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import logging

from garuda import Garuda
from garuda.channels.rest import GAFalconChannel
from garuda.plugins.authentication import GASimpleAuthenticationPlugin
from garuda.plugins.storage import GAMongoStoragePlugin
from garuda.plugins.permissions import GAOwnerPermissionsPlugin


def auth_function(request, session, root_object_class, storage_controller):
    """
    """
    auth = root_object_class()
    auth.api_key = session.uuid
    auth.id = 'root'
    auth.password = None
    return auth


def start(falcon_port, sdk_name, mongo_host, mongo_port, mongo_db, redis_host, redis_port, redis_db):
    """
    """
    channel = GAFalconChannel(port=falcon_port)

    # redis
    redis_info = {'host': redis_host, 'port': redis_port, 'db': redis_db}

    # mongo
    mongo_uri = 'mongodb://%s:%d' % (mongo_host, mongo_port)

    # sdk info
    sdk_infos = [{'identifier': 'default', 'module': sdk_name}]

    # plugins
    storage_plugin = GAMongoStoragePlugin(db_name=mongo_db, mongo_uri=mongo_uri)
    authentication_plugin = GASimpleAuthenticationPlugin(auth_function=auth_function)
    permissions_plugin = GAOwnerPermissionsPlugin()

    garuda = Garuda(sdks_info=sdk_infos,
                    redis_info=redis_info,
                    channels=[channel],
                    plugins=[storage_plugin, authentication_plugin, permissions_plugin],
                    log_level=logging.DEBUG)
    garuda.start()


if __name__ == '__main__':

    garuda_sdk_name = os.environ['GARUDA_SDK_NAME'] if 'GARUDA_SDK_NAME' in os.environ else 'tdldk.v1_0'
    garuda_port = os.environ['GARUDA_PORT'] if 'GARUDA_PORT' in os.environ else 3000
    garuda_mongo_host = os.environ['GARUDA_MONGO_HOST'] if 'GARUDA_MONGO_HOST' in os.environ else '127.0.0.1'
    garuda_mongo_port = os.environ['GARUDA_MONGO_PORT'] if 'GARUDA_MONGO_PORT' in os.environ else 27017
    garuda_mongo_db = os.environ['GARUDA_MONGO_DB'] if 'GARUDA_MONGO_DB' in os.environ else 'tdl'
    garuda_redis_host = os.environ['GARUDA_REDIS_HOST'] if 'GARUDA_REDIS_HOST' in os.environ else '127.0.0.1'
    garuda_redis_port = os.environ['GARUDA_REDIS_PORT'] if 'GARUDA_REDIS_PORT' in os.environ else 6379
    garuda_redis_db = os.environ['GARUDA_REDIS_DB'] if 'GARUDA_REDIS_DB' in os.environ else 6

    start(falcon_port=garuda_port,
          sdk_name=garuda_sdk_name,
          mongo_host=garuda_mongo_host,
          mongo_port=garuda_mongo_port,
          mongo_db=garuda_mongo_db,
          redis_host=garuda_redis_host,
          redis_port=garuda_redis_port,
          redis_db=garuda_redis_db)
