FROM nginx
MAINTAINER Antoine Mercadal <antoine@nuagenetworks.net>

ADD . /sources

RUN cd /sources && \
    ./buildApp -c -v --cappinstalldir="/narwhal" --cappbuilddir="/cappuccino" && \
    ./buildApp -a -v --cappinstalldir="/narwhal" --cappbuilddir="/cappuccino" --setversion="0.0"

ADD ./Build/Deployment/[__APP_NAME__].ready /usr/share/nginx/html